---
kind: pipeline
type: docker
name: lint

platform:
  os: linux
  arch: amd64

steps:
- name: Lint Dockerfiles
  pull: if-not-exists
  image: hadolint/hadolint:latest-debian
  commands:
  - hadolint --version
  - hadolint */Dockerfile

trigger:
  event:
  - pull_request
  - push
  ref:
    exclude:
    - refs/heads/renovate/*

---
kind: pipeline
type: docker
name: test_3-8

platform:
  os: linux
  arch: amd64

steps:
- name: build test
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 3.8/Dockerfile
    dry_run: true
    password:
      from_secret: dockerhub_password_ro
    repo: mwalbeck/python-poetry
    username:
      from_secret: dockerhub_username

trigger:
  event:
  - pull_request

depends_on:
- lint

---
kind: pipeline
type: docker
name: test_3-9

platform:
  os: linux
  arch: amd64

steps:
- name: build test
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 3.9/Dockerfile
    dry_run: true
    password:
      from_secret: dockerhub_password_ro
    repo: mwalbeck/python-poetry
    username:
      from_secret: dockerhub_username

trigger:
  event:
  - pull_request

depends_on:
- lint

---
kind: pipeline
type: docker
name: test_3-10

platform:
  os: linux
  arch: amd64

steps:
- name: build test
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 3.10/Dockerfile
    dry_run: true
    password:
      from_secret: dockerhub_password_ro
    repo: mwalbeck/python-poetry
    username:
      from_secret: dockerhub_username

trigger:
  event:
  - pull_request

depends_on:
- lint

---
kind: pipeline
type: docker
name: test_3-11

platform:
  os: linux
  arch: amd64

steps:
- name: build test
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 3.11/Dockerfile
    dry_run: true
    password:
      from_secret: dockerhub_password_ro
    repo: mwalbeck/python-poetry
    username:
      from_secret: dockerhub_username

trigger:
  event:
  - pull_request

depends_on:
- lint

---
kind: pipeline
type: docker
name: release_3-8

platform:
  os: linux
  arch: amd64

steps:
- name: determine tags
  pull: if-not-exists
  image: mwalbeck/determine-docker-tags
  environment:
    APP_ENV: 3.8
    APP_NAME: POETRY
    DOCKERFILE_PATH: 3.8/Dockerfile
    VERSION_TYPE: docker_env

- name: build and publish
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 3.8/Dockerfile
    password:
      from_secret: dockerhub_password
    repo: mwalbeck/python-poetry
    username:
      from_secret: dockerhub_username

trigger:
  branch:
  - master
  event:
  - push

depends_on:
- lint

---
kind: pipeline
type: docker
name: release_3-9

platform:
  os: linux
  arch: amd64

steps:
- name: determine tags
  pull: if-not-exists
  image: mwalbeck/determine-docker-tags
  environment:
    APP_ENV: 3.9
    APP_NAME: POETRY
    DOCKERFILE_PATH: 3.9/Dockerfile
    VERSION_TYPE: docker_env

- name: build and publish
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 3.9/Dockerfile
    password:
      from_secret: dockerhub_password
    repo: mwalbeck/python-poetry
    username:
      from_secret: dockerhub_username

trigger:
  branch:
  - master
  event:
  - push

depends_on:
- lint

---
kind: pipeline
type: docker
name: release_3-10

platform:
  os: linux
  arch: amd64

steps:
- name: determine tags
  pull: if-not-exists
  image: mwalbeck/determine-docker-tags
  environment:
    APP_ENV: 3.10
    APP_NAME: POETRY
    DOCKERFILE_PATH: 3.10/Dockerfile
    VERSION_TYPE: docker_env

- name: build and publish
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 3.10/Dockerfile
    password:
      from_secret: dockerhub_password
    repo: mwalbeck/python-poetry
    username:
      from_secret: dockerhub_username

trigger:
  branch:
  - master
  event:
  - push

depends_on:
- lint

---
kind: pipeline
type: docker
name: release_3-11

platform:
  os: linux
  arch: amd64

steps:
- name: determine tags
  pull: if-not-exists
  image: mwalbeck/determine-docker-tags
  environment:
    APP_ENV: 3.11
    APP_NAME: POETRY
    CUSTOM_TAGS: latest
    DOCKERFILE_PATH: 3.11/Dockerfile
    VERSION_TYPE: docker_env

- name: build and publish
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 3.11/Dockerfile
    password:
      from_secret: dockerhub_password
    repo: mwalbeck/python-poetry
    username:
      from_secret: dockerhub_username

trigger:
  branch:
  - master
  event:
  - push

depends_on:
- lint

---
kind: signature
hmac: 2baed9a1385bd7f5be1e04564fa804ff9b632abfd87e80d21fb39b8a95ac78f6

...
