---
###############################################################################
kind: pipeline
type: docker
name: lint

steps:
  - name: lint dockerfile
    image: hadolint/hadolint
    commands:
      - hadolint */Dockerfile

trigger:
  event:
    - pull_request
    - push

---
###############################################################################
kind: pipeline
type: docker
name: 3-7_test

steps:
  - name: docker
    image: plugins/docker
    settings:
      dockerfile: 3.7/Dockerfile
      repo: mwalbeck/python-poetry
      dry_run: true

trigger:
  event:
    - pull_request

depends_on:
  - lint

---
###############################################################################
kind: pipeline
type: docker
name: 3-7_build

steps:
  - name: determine tags
    image: mwalbeck/determine-docker-tags
    environment:
      VERSION_TYPE: "docker_env"
      APP_NAME: "POETRY"
      DOCKERFILE_PATH: "3.7/Dockerfile"
      APP_ENV: "3.7"

  - name: build and publish
    image: plugins/docker
    settings:
      dockerfile: 3.7/Dockerfile
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: mwalbeck/python-poetry
  
  - name: notify
    image: plugins/matrix
    settings:
      homeserver: https://matrix.mwalbeck.org
      roomid:
        from_secret: matrix_roomid
      username:
        from_secret: matrix_username
      password:
        from_secret: matrix_password
    when:
      status:
        - success
        - failure

trigger:
  branch:
    - master
  event:
    - push

depends_on:
  - lint

---
###############################################################################
kind: pipeline
type: docker
name: 3-8_test

steps:
  - name: docker
    image: plugins/docker
    settings:
      dockerfile: 3.8/Dockerfile
      repo: mwalbeck/python-poetry
      dry_run: true

trigger:
  event:
    - pull_request

depends_on:
  - lint

---
###############################################################################
kind: pipeline
type: docker
name: 3-8_build

steps:
  - name: determine tags
    image: mwalbeck/determine-docker-tags
    environment:
      VERSION_TYPE: "docker_env"
      APP_NAME: "POETRY"
      DOCKERFILE_PATH: "3.8/Dockerfile"
      APP_ENV: "3.8"

  - name: build and publish
    image: plugins/docker
    settings:
      dockerfile: 3.8/Dockerfile
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: mwalbeck/python-poetry
  
  - name: notify
    image: plugins/matrix
    settings:
      homeserver: https://matrix.mwalbeck.org
      roomid:
        from_secret: matrix_roomid
      username:
        from_secret: matrix_username
      password:
        from_secret: matrix_password
    when:
      status:
        - success
        - failure

trigger:
  branch:
    - master
  event:
    - push

depends_on:
  - lint

---
###############################################################################
kind: pipeline
type: docker
name: 3-9_test

steps:
  - name: docker
    image: plugins/docker
    settings:
      dockerfile: 3.9/Dockerfile
      repo: mwalbeck/python-poetry
      dry_run: true

trigger:
  event:
    - pull_request

depends_on:
  - lint

---
###############################################################################
kind: pipeline
type: docker
name: 3-9_build

steps:
  - name: determine tags
    image: mwalbeck/determine-docker-tags
    environment:
      VERSION_TYPE: "docker_env"
      APP_NAME: "POETRY"
      DOCKERFILE_PATH: "3.9/Dockerfile"
      APP_ENV: "3.9"
      CUSTOM_TAGS: "latest"

  - name: build and publish
    image: plugins/docker
    settings:
      dockerfile: 3.9/Dockerfile
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: mwalbeck/python-poetry
  
  - name: notify
    image: plugins/matrix
    settings:
      homeserver: https://matrix.mwalbeck.org
      roomid:
        from_secret: matrix_roomid
      username:
        from_secret: matrix_username
      password:
        from_secret: matrix_password
    when:
      status:
        - success
        - failure

trigger:
  branch:
    - master
  event:
    - push

depends_on:
  - lint
