---
kind: pipeline
type: docker
name: lint

platform:
  os: linux
  arch: amd64

steps:
- name: Lint Dockerfiles
  pull: if-not-exists
  image: hadolint/hadolint:latest-debian
  commands:
  - hadolint --version
  - hadolint */Dockerfile

trigger:
  event:
  - pull_request
  - push
  ref:
    exclude:
    - refs/heads/renovate/*

---
kind: pipeline
type: docker
name: test_3-9

platform:
  os: linux
  arch: amd64

steps:
- name: build test
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 3.9/Dockerfile
    dry_run: true
    password:
      from_secret: dockerhub_password_ro
    repo: mwalbeck/python-poetry
    username:
      from_secret: dockerhub_username

trigger:
  event:
  - pull_request

depends_on:
- lint

---
kind: pipeline
type: docker
name: test_3-10

platform:
  os: linux
  arch: amd64

steps:
- name: build test
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 3.10/Dockerfile
    dry_run: true
    password:
      from_secret: dockerhub_password_ro
    repo: mwalbeck/python-poetry
    username:
      from_secret: dockerhub_username

trigger:
  event:
  - pull_request

depends_on:
- lint

---
kind: pipeline
type: docker
name: test_3-11

platform:
  os: linux
  arch: amd64

steps:
- name: build test
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 3.11/Dockerfile
    dry_run: true
    password:
      from_secret: dockerhub_password_ro
    repo: mwalbeck/python-poetry
    username:
      from_secret: dockerhub_username

trigger:
  event:
  - pull_request

depends_on:
- lint

---
kind: pipeline
type: docker
name: test_3-12

platform:
  os: linux
  arch: amd64

steps:
- name: build test
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 3.12/Dockerfile
    dry_run: true
    password:
      from_secret: dockerhub_password_ro
    repo: mwalbeck/python-poetry
    username:
      from_secret: dockerhub_username

trigger:
  event:
  - pull_request

depends_on:
- lint

---
kind: pipeline
type: docker
name: test_3-13

platform:
  os: linux
  arch: amd64

steps:
- name: build test
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 3.13/Dockerfile
    dry_run: true
    password:
      from_secret: dockerhub_password_ro
    repo: mwalbeck/python-poetry
    username:
      from_secret: dockerhub_username

trigger:
  event:
  - pull_request

depends_on:
- lint

---
kind: pipeline
type: docker
name: release_3-9

platform:
  os: linux
  arch: amd64

steps:
- name: determine tags
  pull: if-not-exists
  image: mwalbeck/determine-docker-tags
  environment:
    APP_ENV: 3.9
    APP_NAME: POETRY
    DOCKERFILE_PATH: 3.9/Dockerfile
    VERSION_TYPE: docker_env

- name: build and publish
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 3.9/Dockerfile
    password:
      from_secret: dockerhub_password
    repo: mwalbeck/python-poetry
    username:
      from_secret: dockerhub_username

trigger:
  branch:
  - master
  event:
  - push

depends_on:
- lint

---
kind: pipeline
type: docker
name: release_3-10

platform:
  os: linux
  arch: amd64

steps:
- name: determine tags
  pull: if-not-exists
  image: mwalbeck/determine-docker-tags
  environment:
    APP_ENV: 3.10
    APP_NAME: POETRY
    DOCKERFILE_PATH: 3.10/Dockerfile
    VERSION_TYPE: docker_env

- name: build and publish
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 3.10/Dockerfile
    password:
      from_secret: dockerhub_password
    repo: mwalbeck/python-poetry
    username:
      from_secret: dockerhub_username

trigger:
  branch:
  - master
  event:
  - push

depends_on:
- lint

---
kind: pipeline
type: docker
name: release_3-11

platform:
  os: linux
  arch: amd64

steps:
- name: determine tags
  pull: if-not-exists
  image: mwalbeck/determine-docker-tags
  environment:
    APP_ENV: 3.11
    APP_NAME: POETRY
    DOCKERFILE_PATH: 3.11/Dockerfile
    VERSION_TYPE: docker_env

- name: build and publish
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 3.11/Dockerfile
    password:
      from_secret: dockerhub_password
    repo: mwalbeck/python-poetry
    username:
      from_secret: dockerhub_username

trigger:
  branch:
  - master
  event:
  - push

depends_on:
- lint

---
kind: pipeline
type: docker
name: release_3-12

platform:
  os: linux
  arch: amd64

steps:
- name: determine tags
  pull: if-not-exists
  image: mwalbeck/determine-docker-tags
  environment:
    APP_ENV: 3.12
    APP_NAME: POETRY
    DOCKERFILE_PATH: 3.12/Dockerfile
    VERSION_TYPE: docker_env

- name: build and publish
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 3.12/Dockerfile
    password:
      from_secret: dockerhub_password
    repo: mwalbeck/python-poetry
    username:
      from_secret: dockerhub_username

trigger:
  branch:
  - master
  event:
  - push

depends_on:
- lint

---
kind: pipeline
type: docker
name: release_3-13

platform:
  os: linux
  arch: amd64

steps:
- name: determine tags
  pull: if-not-exists
  image: mwalbeck/determine-docker-tags
  environment:
    APP_ENV: 3.13
    APP_NAME: POETRY
    CUSTOM_TAGS: latest
    DOCKERFILE_PATH: 3.13/Dockerfile
    VERSION_TYPE: docker_env

- name: build and publish
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: 3.13/Dockerfile
    password:
      from_secret: dockerhub_password
    repo: mwalbeck/python-poetry
    username:
      from_secret: dockerhub_username

trigger:
  branch:
  - master
  event:
  - push

depends_on:
- lint

---
kind: signature
hmac: 29f7310f8d7d18bed0930ab5d9cfcb4528ee04cf497583a7c1559ddb0aaa2d1d

...
