name: Build and publish

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: docker
    steps:
      - uses: actions/checkout@v6
      - uses: https://github.com/hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: Dockerfile
          recursive: true

  python3_10:
    runs-on: dind
    steps:
      - uses: actions/checkout@v6

      - name: Get docker tags - Docker Hub
        id: dockerhub_tags
        shell: sh
        env:
          VERSION_TYPE: "docker_env"
          APP_NAME: "POETRY"
          APP_ENV: "3.10"
          DOCKERFILE_PATH: "3.10/Dockerfile"
          IMAGE_NAME: "mwalbeck/python-poetry"
        run: |
          determine-docker-tags

      - name: Get docker tags - Forgejo
        id: forgejo_tags
        shell: sh
        env:
          VERSION_TYPE: "docker_env"
          APP_NAME: "POETRY"
          APP_ENV: "3.10"
          DOCKERFILE_PATH: "3.10/Dockerfile"
          IMAGE_NAME: "git.walbeck.it/mwalbeck/python-poetry"
        run: |
          determine-docker-tags
          dockerd &

      - name: Login to Docker Hub
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Forgejo registry
        uses: https://github.com/docker/login-action@v3
        with:
          registry: git.walbeck.it
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
      - name: Build and push
        uses: https://github.com/docker/build-push-action@v6
        with:
          push: true
          file: "3.10/Dockerfile"
          tags: |
            ${{ steps.dockerhub_tags.outputs.tags }}
            ${{ steps.forgejo_tags.outputs.tags }}

  python3_11:
    runs-on: dind
    steps:
      - uses: actions/checkout@v6

      - name: Get docker tags - Docker Hub
        id: dockerhub_tags
        shell: sh
        env:
          VERSION_TYPE: "docker_env"
          APP_NAME: "POETRY"
          APP_ENV: "3.11"
          DOCKERFILE_PATH: "3.11/Dockerfile"
          IMAGE_NAME: "mwalbeck/python-poetry"
        run: |
          determine-docker-tags

      - name: Get docker tags - Forgejo
        id: forgejo_tags
        shell: sh
        env:
          VERSION_TYPE: "docker_env"
          APP_NAME: "POETRY"
          APP_ENV: "3.11"
          DOCKERFILE_PATH: "3.11/Dockerfile"
          IMAGE_NAME: "git.walbeck.it/mwalbeck/python-poetry"
        run: |
          determine-docker-tags
          dockerd &

      - name: Login to Docker Hub
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Forgejo registry
        uses: https://github.com/docker/login-action@v3
        with:
          registry: git.walbeck.it
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
      - name: Build and push
        uses: https://github.com/docker/build-push-action@v6
        with:
          push: true
          file: "3.11/Dockerfile"
          tags: |
            ${{ steps.dockerhub_tags.outputs.tags }}
            ${{ steps.forgejo_tags.outputs.tags }}

  python3_12:
    runs-on: dind
    steps:
      - uses: actions/checkout@v6

      - name: Get docker tags - Docker Hub
        id: dockerhub_tags
        shell: sh
        env:
          VERSION_TYPE: "docker_env"
          APP_NAME: "POETRY"
          APP_ENV: "3.12"
          DOCKERFILE_PATH: "3.12/Dockerfile"
          IMAGE_NAME: "mwalbeck/python-poetry"
        run: |
          determine-docker-tags

      - name: Get docker tags - Forgejo
        id: forgejo_tags
        shell: sh
        env:
          VERSION_TYPE: "docker_env"
          APP_NAME: "POETRY"
          APP_ENV: "3.12"
          DOCKERFILE_PATH: "3.12/Dockerfile"
          IMAGE_NAME: "git.walbeck.it/mwalbeck/python-poetry"
        run: |
          determine-docker-tags
          dockerd &

      - name: Login to Docker Hub
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Forgejo registry
        uses: https://github.com/docker/login-action@v3
        with:
          registry: git.walbeck.it
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
      - name: Build and push
        uses: https://github.com/docker/build-push-action@v6
        with:
          push: true
          file: "3.12/Dockerfile"
          tags: |
            ${{ steps.dockerhub_tags.outputs.tags }}
            ${{ steps.forgejo_tags.outputs.tags }}

  python3_13:
    runs-on: dind
    steps:
      - uses: actions/checkout@v6

      - name: Get docker tags - Docker Hub
        id: dockerhub_tags
        shell: sh
        env:
          VERSION_TYPE: "docker_env"
          APP_NAME: "POETRY"
          APP_ENV: "3.13"
          DOCKERFILE_PATH: "3.13/Dockerfile"
          IMAGE_NAME: "mwalbeck/python-poetry"
        run: |
          determine-docker-tags

      - name: Get docker tags - Forgejo
        id: forgejo_tags
        shell: sh
        env:
          VERSION_TYPE: "docker_env"
          APP_NAME: "POETRY"
          APP_ENV: "3.13"
          DOCKERFILE_PATH: "3.13/Dockerfile"
          IMAGE_NAME: "git.walbeck.it/mwalbeck/python-poetry"
        run: |
          determine-docker-tags
          dockerd &

      - name: Login to Docker Hub
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Forgejo registry
        uses: https://github.com/docker/login-action@v3
        with:
          registry: git.walbeck.it
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
      - name: Build and push
        uses: https://github.com/docker/build-push-action@v6
        with:
          push: true
          file: "3.13/Dockerfile"
          tags: |
            ${{ steps.dockerhub_tags.outputs.tags }}
            ${{ steps.forgejo_tags.outputs.tags }}

  python3_14:
    runs-on: dind
    steps:
      - uses: actions/checkout@v6

      - name: Get docker tags - Docker Hub
        id: dockerhub_tags
        shell: sh
        env:
          VERSION_TYPE: "docker_env"
          APP_NAME: "POETRY"
          APP_ENV: "3.14"
          DOCKERFILE_PATH: "3.14/Dockerfile"
          IMAGE_NAME: "mwalbeck/python-poetry"
        run: |
          determine-docker-tags

      - name: Get docker tags - Forgejo
        id: forgejo_tags
        shell: sh
        env:
          VERSION_TYPE: "docker_env"
          APP_NAME: "POETRY"
          APP_ENV: "3.14"
          DOCKERFILE_PATH: "3.14/Dockerfile"
          IMAGE_NAME: "git.walbeck.it/mwalbeck/python-poetry"
        run: |
          determine-docker-tags
          dockerd &

      - name: Login to Docker Hub
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Forgejo registry
        uses: https://github.com/docker/login-action@v3
        with:
          registry: git.walbeck.it
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
      - name: Build and push
        uses: https://github.com/docker/build-push-action@v6
        with:
          push: true
          file: "3.14/Dockerfile"
          tags: |
            ${{ steps.dockerhub_tags.outputs.tags }}
            ${{ steps.forgejo_tags.outputs.tags }}
