FROM python:3.9.1-slim-buster

# renovate: datasource=pypi depName=poetry versioning=semver
ENV POETRY_VERSION v1.1.4

RUN set -ex; \
    \
    pip install poetry==$DETERMINE_DOCKER_TAGS_VERSION;

CMD [ "poetry" ]
