FROM python:3.9.1-alpine3.12

# renovate: datasource=pypi depName=poetry versioning=semver
ENV POETRY_VERSION v1.1.4

RUN set -ex; \
    \
    apk add --no-cache \
        gcc \
        libressl-dev \
        musl-dev \
        libffi-dev; \
    \
    pip install poetry==$POETRY_VERSION; \
    \
    apk del \
        gcc \
        libressl-dev \
        musl-dev \
        libffi-dev;

CMD [ "poetry" ]
